### ISSUE TITLE
Show current number of cops online & allow other mods access to that

### ISSUE THREAD

**Issue by ghost** [FiveM-Scripts/Cops_FiveM#86]
One thing that would be extremely helpful is the ability to see how many cops are in service at any given time. And some way to determine this via code before allowing banks to be robbed, etc.

**Comment by Kyominii** [comment]
Already available, see https://github.com/Kyominii/Cops_FiveM_dev/blob/master/police/config/config.lua#L14

**Comment by JaxsenL** [comment]
You are talking about something that will do things like

Registere the number of players clocked in to some form of temporary database so that when (for example) you open up your F5 menu you might have a counter for clocked in cops at the bottom to see just how many there are instead of expanding the map and counting? and so a function can work something like this?
```
local copsonduty = {}
function CopsClockedIn ()
     if (#copsonduty < config.minimumCopsRequired) then 
          setBanksRobAble = false
     end
end
```
The issue with that is that copsfivem does not have banks built in as RobAble or anything like that; however, if this were to become a function it would be useful for any future upgrades.

**Comment by Kyominii** [comment]
Okay, I'll work on it

**Comment by ghermans** [comment]
Added this to v2.0, still not 100% satisfied so it could change before we push it to Github.

![20180203000647_1](https://user-images.githubusercontent.com/1594411/36229994-4e6e3142-11d9-11e8-9838-dfa0376ccd53.jpg)
